Repository cncf/hugo-netlify-starter, pull requests merged in 2021-07, with the labels that each got.

#84 README: linewrap long lines before making other changes
  README.md
Labels: cleanup/refactoring

#85 Drop any mention of yarn, since we'll be using npm
  .gitignore
  Makefile
  README.md
  content/_index.md
Labels: cleanup, infrastructure

#88 Add .nvmrc codifying the need for latest Node.js LTS release
  .nvmrc
Labels: infrastructure

#89 Gitignore tweaks: support /public as a symlink
  .gitignore
Labels: infrastructure

#90 css.html template cleanup
  layouts/partials/css.html
Labels: cleanup, infrastructure

#94 Clean up npm package dependencies
  package.json
Labels: infrastructure

#99 fix left alignment
  assets/sass/custom.sass
Labels: cleanup

#98 Render links with given destination w/o rewriting
  layouts/_default/_markup/render-link.html
Labels: infrastructure

#105 Support running build:preview locally
  package.json
Labels: infrastructure
